version: '2.1'

services:
  tunachain-shell:
    image: hyperledger/sawtooth-all
    container_name: tunachain-shell
    depends_on:
       - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  tunachain-server:
    build:
      context: .
      #target: development
      dockerfile: ./server/Dockerfile
    image: hyperledger/tunachain-server
    container_name: tunachain-server
    volumes:
       - ./server:/project/sawtooth-tuna/server
       - /project/sawtooth-tuna/server/node_modules
    command: npm run start
    ports:
       - 3005:3005
    depends_on:
       - rest-api
  

  tunachain-tp:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: sawtooth-tunachain-tp
    container_name: tunachain-tp
    volumes:
      - .:/project/sawtooth-tuna
    depends_on:
      - validator
    entrypoint: |
      bash -c "
        sleep 1
        tunachain-tp -vv -C tcp://validator:4004
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator
    expose:
      - 4004
      - 8800
    ports:
      - '4004:4004'
    entrypoint: "bash -c \"\
      if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch; \
      fi; \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

    #volumes:
     # - ./database/bcdata/data:/var/lib/sawtooth
      #- ./database/bcdata/keys:/etc/sawtooth/keys
      #- ./database/bcdata/userKeys:/root/.sawtooth/keys
      #- ./database/bcdata/logs:/var/log/sawtooth
  
  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

#volumes:
#    db:
#      driver: local    


